config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :items, :path => "ma_photo"
  resources :carts, :path => "mon_panier"
  resources :orders, :path => "ma_commande"
  resources :users, :path => "utilisateur"
  root to: "items#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord

  has_many :items
  belongs_to :user
  
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  has_many :users
  has_many :carts
end

app/models/item.rb
class Item < ApplicationRecord

  has_many :carts
  has_many :users, through: :carts

end

app/models/order.rb
class Order < ApplicationRecord

  has_many :cart_items
  belongs_to :user


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
        
  has_many :carts
  after_create :user_cart
  

  def user_cart
    @cart = Cart.create(user_id: self.id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :current_cart

  private
    def current_cart
      if session[:cart_id]
        cart = Cart.find_by(:id => session[:cart_id])
        if cart.present?
          @current_cart = cart
        else
          session[:cart_id] = nil
        end
      end

      if session[:cart_id] == nil
        @current_cart = Cart.create
        session[:cart_id] = @current_cart.id
      end
    end
end

 

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!


  def show
    @item = Item.all
    @carts = Cart.find_by(user_id: current_user.id)
    @cart = current_cart
    @cartitem = CartItem.all
    if current_user.id == @carts.id

    else 
      redirect_to cart_path(current_user.id)
    end
  end
  
 
  def update
    @cart = Cart.find_by(user_id: current_user.id)
    new_item = CartItem.create(cart_id: @cart.id, item_id: params[:id])
    redirect_to root_path
    
  end

  def destroy
    @user = current_user
    @item = Item.find_by(id: params[:id])
    @cart = Cart.find_by(user_id: current_user.id)
    @cart_item = CartItem.find_by(cart_id: @cart.id, item_id: @item.id).destroy
    redirect_to cart_path(current_user.id)
  end



end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def new
    @items = Item.new
  end 

  def create
    @items = Item.create
  end 

  def show 
    @item = Item.find(params[:id])
    @user = current_user
  end 
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

    def index
        @amount = Order.last.total
        @stripe_amount = (@amount).to_i
    end
    
    def show
        @user = User.all
        @amount = Order.last.total
        @stripe_amount = (@amount).to_i

    end

    def confirmation_email_send
        variable = Mailjet::Send.create(messages: [{
          'From'=> {
            'Email'=> 'louis.grandjean99@gmail.com',
            'Name'=> 'Louis'
          },
          'To'=> [
            {
              'Email'=> User.find(Order.last.user_id).email,
              'Name'=> User.find(Order.last.user_id).email
            }
          ],
          'Subject'=> 'Order confirmation',
          'TextPart'=> 'Order confirmation',
          'HTMLPart'=> "<section class='page-wrapper success-msg'>
          <div class='container'>
            <div class='row'>
              <div class='col-md-6 col-md-offset-3'>
                <div class='block text-center'>
                  <i class='tf-ion-android-checkmark-circle'></i>
                  <h2 class='text-center'>Hi #{User.find(Order.last.user_id).email} Thank you! For your payment</h2>
                  <p>Thank you! For your payment of #{Order.last.total} $</p>
                  <a href='shop.html' class='btn btn-main mt-20'>Continue Shopping</a>
                </div>
              </div>
            </div>
          </div>
        </section>",
          'CustomID' => 'AppGettingStartedTest'
        }]
        )
        p variable.attributes['Messages']
      #UserMailer.confirmation_email(User.find(Order.last.user_id)).deliver_now
    end

    def admin_email
        variable = Mailjet::Send.create(messages: [{
            'From'=> {
              'Email'=> 'louis.grandjean99@gmail.com',
              'Name'=> 'Louis'
            },
            'To'=> [
              {
                'Email'=> 'chatonchat@yopmail.com',
                'Name'=> 'Administrateur'
              }
            ],
            'Subject'=> 'Order confirmation',
            'TextPart'=> 'Order confirmation',
            'HTMLPart'=> "<section class='page-wrapper success-msg'>
            <div class='container'>
              <div class='row'>
                <div class='col-md-6 col-md-offset-3'>
                  <div class='block text-center'>
                    <i class='tf-ion-android-checkmark-circle'></i>
                    <h2 class='text-center'>Hi #{User.find(Order.last.user_id).email} has make a purchase</h2>
                    <p>Total: #{Order.last.total} $</p>
                    <p>Id: #{Order.last.id}</p>
                    <a href='shop.html' class='btn btn-main mt-20'>Continue Shopping</a>
                  </div>
                </div>
              </div>
            </div>
          </section>",
            'CustomID' => 'AppGettingStartedTest'
          }]
          )
          p variable.attributes['Messages']
    end


    def create
        @cart_item = CartItem.find_by(cart_id: current_user.id)
         @order = Order.create(cart_item_id: @cart_item, user_id: current_user.id, total: $total)
            @cart = CartItem.find_by(cart_id: current_user.id)
            @carts = CartItem.all

            
            @carts.each do |item|
                if current_user.id == @cart.cart_id
                item.destroy
                end 
            end
        
        # Before the rescue, at the beginning of the method
            @amount = Order.last.total
            @stripe_amount = (@amount).to_i
            begin
            customer = Stripe::Customer.create({
            email: params[:stripeEmail],
            source: params[:stripeToken],
            })
            charge = Stripe::Charge.create({
            customer: customer.id,
            amount: @stripe_amount,
            description: "Achat d'un produit",
            currency: 'eur',
            })
            redirect_to orders_path
            confirmation_email_send
            admin_email

            rescue Stripe::CardError => e
            flash[:error] = e.message
            redirect_to order_path(current_user.id)
            end
        # After the rescue, if the payment succeeded
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def create
  @user = User.new
  
end

def show

end

def edit

end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/show.html.erb
<section class="page-header">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="content">
					<h1 class="page-name">Panier</h1>
					<ol class="breadcrumb">
						<li><a href="/">Accueil</a></li>
						<li class="active">Panier</li>
					</ol>
				</div>
			</div>
		</div>
	</div>
</section>




<div class="page-wrapper">
<div class="cart shopping">
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <div class="block">
          <div class="product-list">
            <form method="post">
              <table class="table">
                <thead>
                  <tr>
                    <th class="">Nom du produit</th>
                    <th class="">Prix du produit</th>
                    <th class="">Actions</th>
                  </tr>
                </thead>
              
                <% $total = 0 %>
              <% @cartitem.each do |index| %>
                
                <% if (current_user.id == index.cart_id)%>
                
                <tbody>
                  <tr class="">
                    <td class="">
                      <div class="product-info">
                        <img width="80" src="images/shop/cart/cart-1.jpg" alt="">
                        <a href="#!"><%= Item.find(index.item_id).title%></a>
                      </div>
                    </td>
                    <td class=""><%= @price = Item.find(index.item_id).price.to_i%></td>
                    <td class="">
                    <% @current = Item.find(index.item_id).id %>
                      <%= link_to "Supprimer", cart_path(@current), method: :delete, class: "product-remove" %>
                    </td>
                    
                    <% $total += @price %>
                </tbody>
                
                <%end%>
              <% end %>
              <p>Prix total : <%= $total %></p>
       

              </table>
                <%= link_to "Confirmer le panier", orders_path, method: :post, class:"btn btn-main pull-right"%>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>

app/views/items/index.html.erb
<%= render 'layouts/slider'  %>
	<div class="container">
		<div class="row">
	
			<div class="title text-center">
				<h2>Nos photos de chats</h2>
			</div>
	</div>
		
		<div class="row">
		<% @items.each do |item| %>
		<div class="col-md-3">
		<div class="product-item">
	
		
			<div class="product-thumb">
			
				<img class="img-responsive" src="<%= item.image_url %>" alt="product-img">
				
				<div class="preview-meta">
				<%if current_user%>
            <%= link_to "Ajouter au panier", cart_path(item.id), method: :put, class: "btn btn-main mt-20", style: "margin-bottom: 5%;"%>
            <%else%>
            <%= link_to "Connectez-vous", user_session_path, class: "btn btn-main mt-20", style: "margin-bottom: 5%;"%>
	      <%end%>
					
			</div>
		</div>
			<div class="product-content">
				<h4><%= link_to item.title, item_path(item.id)%></h4>
				<p class="price"><%= item.price%>€</p>
				
			</div>
		
	
	
	
	</div>

	</div>
	<% end %>
	</div>
	</div>
	</div>
			




			

app/views/items/show.html.erb
<% items = Item.find(params[:id]) %>

<div class="modal-content">


<div class="container">
<div class="row">
    
    
<div class="row mt-20">

    <div class="col-md-5">
        <div class="single-product-slider">     
            <div class="item active">
            <img src="<%= items.image_url %>" alt="" data-zoom-image="images/shop/single-products/product-1.jpg">
            </div>
            </div>
        </div>
    </div>
    <div class="col-md-7">
        <div class="single-product-details">
            <h2><%= items.title%></h2>
            <p class="product-price"><%= items.price%>€</p>
            
            <p class="product-description mt-20">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laborum ipsum dicta quod, quia doloremque aut deserunt commodi quis. Totam a consequatur beatae nostrum, earum consequuntur? Eveniet consequatur ipsum dicta recusandae.
            </p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nesciunt, velit, sunt temporibus, nulla accusamus similique sapiente tempora, at atque cumque assumenda minus asperiores est esse sequi dolore magnam. Debitis, explicabo.</p>
            
            <%if current_user%>
            <%= form_tag cart_path(action: 'update'), method: "put" do %>
                <%= submit_tag "Ajouter au panier", class: "btn btn-main mt-20", style: "margin-bottom: 5%;"%> 
                <% end %>
            <%else%>
            <%= link_to "Connectez-vous", user_session_path, class: "btn btn-main mt-20", style: "margin-bottom: 5%;"%>
	        <%end%>
        </div>
   </div>
   </div>

   </div>
    
   </div>    
                       

app/views/layouts/_footer.html.erb
  <section class="">
  <!-- Footer -->
  <footer class="text-center text-dark" style="background-color: rgba(0, 0, 0, 0.02);">
  
    <!-- Grid container -->
    <div class="container p-4 pb-0">
      <!-- Section: CTA -->
      <%if !current_user%>
      <section class="">
        <p class="d-flex justify-content-center align-items-center text-dark" font-family="AustinBold">
          <span class="me-1" font-family="AustinBold">INSCRIVEZ-VOUS GRATUITEMENT :</span>
          <%= button_to "inscription", new_user_registration_path, class:"btn btn-main mt-20 me-1", style:"margin-bottom: 2%;", :method => :get %>
          
        </p>
      </section>
      <!-- Section: CTA -->
    </div>
    <!-- Grid container -->
    <%else%>
    <section class="">
        <p class="d-flex justify-content-center align-items-center text-dark" font-family="AustinBold">
          <span class="me-1" font-family="AustinBold">MERCI D'AVOIR FAIT CONFIANCE À NOS CHATONS :</span>
        </p>
        <p class="d-flex justify-content-center align-items-center text-dark" font-family="AustinBold">Pour toute réclamation, veuillez nous adresser un mail à</p>
        <p class="d-flex justify-content-center align-items-center text-dark" font-family="AustinBold"><a>  contact@chatonchat.com</a></p>
      </section>
      <!-- Section: CTA -->
    </div>
    <%end%>
    <br>
    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.03);">
      © 2020 Copyright:
      <a class="text-dark" href="https://mdbootstrap.com/">MKBugnes.com</a>
    </div>
    <!-- Copyright -->
  </footer>
  <!-- Footer -->
</section>

app/views/layouts/_navbar.html.erb
<section class="top-header">
	<div class="container">
		<div class="row">
			<div class="col-md-4 col-xs-12 col-sm-4">
				<div class="contact-number">
					<i class="tf-ion-ios-telephone"></i>
					<span>03.45.45.45.45</span>
				</div>
			</div>
			<div class="col-md-4 col-xs-12 col-sm-4">
				<!-- Site Logo -->
				<div class="logo text-center">
					<a href="/">
						<!-- replace logo here -->
						<svg width="135px" height="29px" viewBox="0 0 170 29" version="1.1" xmlns="http://www.w3.org/2000/svg"
							xmlns:xlink="http://www.w3.org/1999/xlink">
							<g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd" font-size="40"
								font-family="AustinBold, Austin" font-weight="bold">
								<g id="Group" transform="translate(-108.000000, -297.000000)" fill="#000000">
									<text id="AVIATO">
										<tspan x="108.94" y="325">CHATON </br></tspan>
                    <svg width="135px" height="29px" viewBox="0 0 170 29" version="1.1" xmlns="http://www.w3.org/2000/svg"
							xmlns:xlink="http://www.w3.org/1999/xlink">
							<g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd" font-size="40"
								font-family="AustinBold, Austin" font-weight="bold">
								<g id="Group" transform="translate(-108.000000, -297.000000)" fill="#000000">
									<text id="AVIATO">
                    <tspan x="135.94" y="325">CHAT</tspan>
									</text>
								</g>
							</g>
						</svg>
					</a>
				</div>
			</div>
			<div class="col-md-4 col-xs-12 col-sm-4">
				<!-- Cart -->
				<ul class="top-menu text-right list-inline">
					<li class="dropdown cart-nav dropdown-slide">
						<p><i class="tf-ion-android-cart"></i>Lyon</p>
					</li><!-- / Cart -->
				</ul><!-- / .nav .navbar-nav .navbar-right -->
			</div>
		</div>
	</div>
</section><!-- End Top Header Bar -->

<!-- OUR NAVBAR -->

<section class="menu">
<nav class="navbar navigation">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
  <div class="textcenter">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <%= link_to "Accueil", root_path, class: "nav-link text-black" %>
      </li>
	  <%if current_user%>
      <li class="nav-item">
        <%=link_to "Mon panier",cart_path(current_user.id), class: "nav-link text-black" %>
      </li>
	  <%end%>
    <%if current_user%>
      <li class="nav-item">
		<%=link_to "Mes chats et moi", user_path(current_user.id), class: "nav-link text-black" %>
      </li>
      <%end%>
      <% if !user_signed_in? %>
      <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle text-black" href="#" id="navbarDropdown" data-hover="dropdown" data-delay="350" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Connexion / Inscription <span class="tf-ion-ios-arrow-down"></span>
          </a>
          
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><%= link_to "Inscription", new_user_registration_path, class: "dropdown-item"%></li>
            <li><hr class="dropdown-divider"></li>
            <li><%= link_to "Connexion", new_user_session_path, class: "dropdown-item"%></li>
          </ul>
        </li>
      <% else %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle text-black" href="#" id="navbarDropdown" data-hover="dropdown" data-delay="350" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Se déconnecter <span class="tf-ion-ios-arrow-down"></span> 
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">        
          <li><%= link_to "Déconnexion",  destroy_user_session_path, method: :delete, class: "dropdown-item"%></li>          
        </li>
       <% end %>
    </ul>
    </div>
  </div>
</nav>
</section>

app/views/layouts/_slider.html.erb
<div class="hero-slider">
  <div class="slider-item th-fullpage hero-area" style="background-image: url(https://c1.wallpaperflare.com/preview/44/156/841/cat-white-cat-lay-pets.jpg);">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 text-center">
        <svg width="135px" height="29px" viewBox="0 0 170 29" version="1.1" xmlns="http://www.w3.org/2000/svg"
							xmlns:xlink="http://www.w3.org/1999/xlink">
							<g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd" font-size="40"
								font-family="AustinBold, Austin" font-weight="bold">
								<g id="Group" transform="translate(-108.000000, -297.000000)" fill="#000000">
          <h2 data-duration-in=".3" data-animation-in="fadeInUp" data-delay-in=".1" font-size="40"
          font-family="AustinBold, Austin">NOTRE PROMESSE</h2>
          </g> </g> </svg>
          <svg width="135px" height="29px" viewBox="0 0 170 29" version="1.1" xmlns="http://www.w3.org/2000/svg"
							xmlns:xlink="http://www.w3.org/1999/xlink">
							<g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd" font-size="40"
								font-family="AustinBold, Austin" font-weight="bold">
								<g id="Group" transform="translate(-108.000000, -297.000000)" fill="#000000">
          <h2 data-duration-in=".3" data-animation-in="fadeInUp" data-delay-in=".1" font-size="40"
          font-family="AustinBold, Austin">____<br>Des chatons, des chats et des ronrons <br>__<br> Rien que pour vous</h3><br></h2>
          </g> </g> </svg>
        </div>
      </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chatonchat</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  
    <%= render 'layouts/navbar'%>
    
    <%= yield %>
    

    <%= render 'layouts/footer'%>

</html>

app/views/orders/index.html.erb
<section class="page-wrapper success-msg">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <div class="block text-center">
        	<i class="tf-ion-android-checkmark-circle"></i>
          <h2 class="text-center">Merci de votre commande !</h2>
          <p>BRAVO ! Votre payement de <%= @stripe_amount %> € a bien été accepté ! Miaou</p>
          <a href="/" class="btn btn-main mt-20">Retour au shop</a>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/orders/show.html.erb
<div class="page-wrapper">
   <div class="checkout shopping">
   <div class="jumbotron mr-auto ml-auto">
      <div class="container">
         <div class="row">
            <div class="col-md-6">
               <div class="product-checkout-details">
                  <div class="block">
                     <h4 class="widget-title">Résumé de la Commande</h4>
                     <div class="media product-card">
                        <a class="pull-left" href="product-single.html">
                        </a>
                        <div class="media-body">
                           <p class="price">1 x <%=Order.last.total%></p>
                        </div>
                     </div>
                     <div class="discount-code">
                        <p>Have a discount ? <a data-toggle="modal" data-target="#coupon-modal" href="#!">enter it here</a></p>
                     </div>
                     <ul class="summary-prices">
                        <li>
                           <span>Subtotal:</span>
                           <span class="price"><%=Order.last.total%></span>
                        </li>
                        <li>
                           <span>Shipping:</span>
                           <span>Free</span>
                        </li>
                     </ul>
                     <div class="summary-total">
                        <span>Total</span>
                        <span><%=Order.last.total%></span>
                     </div>
                     <div class="verified-icon">
                     </div>
                  </div>
               </div>
            </div>
         </div>

<div class="col-md-6">
<%= form_tag orders_path do %>
   <article>
     <% if flash[:error].present? %>
       <div id="error_explanation">
         <p><%= flash[:error] %></p>
       </div>
     <% end %>
     <label class="amount">
       <span>Amount: <%= @stripe_amount %>€</span>
     </label>
   </article>
   <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
       data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
       data-description="Achat d'un produit"
       data-amount= <%= @stripe_amount * 100 %>
       data-locale="auto">
   </script>
   <% end %>
   </div>
   </div>
   </div>
   </div>
</div>

app/views/users/show.html.erb
<section class="user-dashboard page-wrapper">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="dashboard-wrapper user-dashboard">
					<div class="media">
						
						<div class="media-body">
							<h2 class="media-heading">Bonjour <%=User.find(params[:id]).email%></h2>
							<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde, iure, est. Sit mollitia est maxime! Eos
								cupiditate tempore, tempora omnis. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Enim, nihil. </p>
						</div>
					</div>
					<div class="total-order mt-20">
						<h4>Total Orders</h4>
						<div class="table-responsive">
							<table class="table">
								<thead>
									<tr>
										<th>Order ID</th>
										<th>Date</th>
										<th>Total Price</th>
                                        <th>Status</th>
									</tr>
								</thead>
								<tbody>

								<% @order = Order.all %>
								<% @order.each do |index| %>

								<% if (current_user.id == index.user_id)%>
          
								
									<tr>
										<td><%=index.id%></td>
										<td><%=index.created_at%></td>
										<td><%=index.total%> $</td>
                                        <td style="color:orange;">Pending</td>
									</tr>
									<%end%>
									<%end%>
								</tbody>
							</table>	
							<a><%= link_to "Editer le profil",  edit_user_registration_path, class: "btn btn-main pull-right"%></a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	
</section>